### ISSUE TITLE
[M1] Project Introduction

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#1]

**Comment by TheRealDexipher** [comment]
In the train operation division, work allocation is assigned weekly every Monday. Therefore, we plan to have an interactive and visualistic workload management web application created for managers to manage employees with ease. This will help ensure employees have an equal amount of workload throughout with their preferred timing indicated for the managers to take into consideration. In this section, you will find the product scope and related background research that was reviewed along with the references, as well as the intended audience and document overview.
