### ISSUE TITLE
[M1] Product Functionality

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#10]

**Comment by TheRealDexipher** [comment]
PF1: The scheduling platform shall have administrative access.
PF2: The scheduling platform shall have manager access.
PF3: The scheduling platform shall have staff access.
PF4: The scheduling platform allows users to perform schedule planning.
PF5: The scheduling platform allows users to indicate their availability.
PF6: The scheduling platform allows users to reject jobs allocated to them.
PF7: The scheduling platform shall display staff schedule information.
