### ISSUE TITLE
[M1] Assumption and Dependencies

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#11]

**Comment by TheRealDexipher** [comment]
The assumed factors include the following:
A1: The number of carriages per train is not taken into consideration.
A2: IT Admin can only create and manage manager and staff accounts.
A3: Employees are not allowed to state their job preferences as they have fixed job scopes.

The dependent factors include the following:
F1: The train company has a total number of 70 workers. There are 10 engine drivers, 6 train conductors, 24 assistant conductors, and 30 cleaners.
