### ISSUE TITLE
[M1] User Interface Requirements

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#13]

**Comment by TheRealDexipher** [comment]
![Image](https://user-images.githubusercontent.com/76478315/192127455-1ef91aac-7539-4625-9997-0fa2da987bde.png)

As shown in Figure 2, in the login interface, employees log in using their unique employee ID and password to have authorised access to the system. Employees who forget their login password are able to make a replacement by clicking on the “Forget Password” button.



![Image](https://user-images.githubusercontent.com/76478315/192127467-38d220c5-27c1-4431-81d3-ccd51ce0e95b.png)

As shown in Figure 3, on the manager landing page, the top 3 lowest workload staff, names, job assigned and working hours of all employees are displayed. Staff with over 40 hours of job allocation are highlighted for the manager’s reference to aid in the process of assigning jobs. 



![Image](https://user-images.githubusercontent.com/76478315/192127474-e946ae5f-43e9-4345-b7df-db2368b72d91.png)

As shown in Figure 4, the manager can click on the ‘Job Allocation’ tab and allocate job to staffs by picking the day of the week from the dropdown box and indicate the job assignments according to employee name. The manager can then click on ‘Save’ button to update the weekly schedule.
