### ISSUE TITLE
[M1] Use Case Model

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#14]

**Comment by TheRealDexipher** [comment]
Use Case Model


![Image](https://user-images.githubusercontent.com/76478315/191670344-0ff4732e-26f9-47d7-96c6-d8f895e77b69.png)


UC1: Allocate Jobs
UC2: Reallocate Jobs
UC3: View Staff Availability
UC4: View Staff Workload
UC5: View Workload
UC6: View Job Assignments
UC7: Reject Assigned Job
UC8: Submit Availability
UC9: Edit Availability
UC10: View availability
UC11: Create Accounts
UC12: Delete Accounts
UC13: Edit Accounts
UC14: View Accounts
