### ISSUE TITLE
[M1] Software Estimation

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#18]

**Comment by TheRealDexipher** [comment]
![Image](https://user-images.githubusercontent.com/76478315/192127608-a8cbf9f5-eb0c-4ea3-b4aa-4774218329e4.png)

From Figure 6, the Total Unadjusted Points (UUCW) is calculated by adding the unadjusted use case weight with the actor's weight as shown in figure 5. Hence, the calculation of transactions in our use case description is adding 95 with 9, which equals to 104.


![Image](https://user-images.githubusercontent.com/76478315/192127617-a9bee49a-565a-46c0-971c-e7216ed2e014.png)

In our workload management system, the 3 actors namely the administrator, manager and staff are identified as complex actors as shown in Figure 7. The Total Unadjusted Points, UUCW= 33 = 9. 

For TCF, there is a degree of influence from 0 to 5, with 0 being irrelevant and 5 being essential.

![Image](https://user-images.githubusercontent.com/76478315/192127628-46719b93-85d2-4800-8130-890e84d6a71d.png)

From Figure 8, the Degree of Influence (DI), calculated by using the weight multiplied by the degree of influence, is 42. Using the formula, TCF=0.6+0.01DI. Therefore, TCF=0.6+0.0142=1.02.

The UCP is calculated by adding the transactions of Use Cases with the actor weight, which forms the total unadjusted points (UUCW), and multiplying together with both TCF and EF. The formula is UCP=UUCWTCFEF=1041.020.89=94.411294.4.
