### ISSUE TITLE
[M1] Project Management

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#19]

**Comment by TheRealDexipher** [comment]
1 Project Conception and Initiation
1.1 GitHub Set-up
1.1.1 GitHub Project Board
1.1.1.1 GitHub Backlog
1.1.1.2 GitHub To-Do (HIGH Priority)
1.1.1.3 GitHub To-Do (MEDIUM Priority)
1.1.1.4 GitHub To-Do (LOW Priority)
1.1.1.5 GitHub In-Progress
1.1.1.6 GitHub Completed
1.1.2 GitHub Wiki Page
1.2  Slack Channel Creation
1.2.1 Distribution of Individual Roles (Eg. Back End Developer, QA Engineer, UI/UX Designer)

2 Requirements Engineering
2.1 Client Meeting
2.1.1 Client Meeting Questions
2.1.2 Meeting Minutes
2.2 Use Case Diagram
2.3 Use Case Descriptions
2.4 Product Scope
2.5 Related Background Literature
2.6 Intended Audience and Document Overview
2.7 Product Overview
2.8 Product Functionality
2.9 Assumptions and Dependencies
2.10 Functional Requirements
2.11 Non-Functional Requirements
2.12 Performance Requirements
2.13 Safety and Security Requirements
2.14 Complete M1 Report
2.15 Class Diagram

3 Project Estimation
3.1 Identifying Transactions in Use Case Descriptions
3.2 Identification of Actors
3.3 Calculate TCF and EF
3.4 Calculate Total Unadjusted Use Case Weight
3.5 Work Breakdown Structure (WBS)
3.6 Gantt Chart

4 Project Design, Testing Maintenance
4.1 Construct Project Wireframe
4.2 Setup MySQL as a database to store login details, Staff availabilities, Work allocation
4.3 Login Page
4.4 Landing Page
4.4.1 Manager Landing Page
4.4.2 Staff Landing Page
4.5 Work Allocation Page
4.6 Availabilities of Staff
4.6.1 Add Availabilities 
4.6.2 Edit Availabilities 
4.7 Staff Job Preference
4.8 IT Administration Add/Remove System Page
4.8.1 Adding Staff/Manager
4.8.2 Deleting Staff/Manager
4.8.3 Editing Staff/Manager
4.9 Deployment of Web Application
4.10 Providing Maintenance and Support After Deployment (5 Years)



![Image](https://user-images.githubusercontent.com/76478315/192127662-6519c5d4-74b9-4644-816b-81961ddb8653.png)

Link below is the excel sheet of the Gantt Chart for better reference:
https://docs.google.com/spreadsheets/d/17UHv1GhxnWmIXheX6lhm3UxEy_XxGol6IqPm2gdGQa0/edit?usp=sharing
