### ISSUE TITLE
[M1] Related Background Literature

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#2]

**Comment by TheRealDexipher** [comment]
Regardless of any enterprise, a fair and functional schedule forms the core of a company by keeping track of employees' time and utilizing it in the most optimal way (Bhadani, 2022). Having an efficient and effective scheduling system in place is important for businesses to operate seamlessly moving forward while staying productive (Mitrefinch, 2016). An effective scheduling system may include options for employees to submit their availability, job preferences, and assigning schedules such that there is fair treatment for all staff. Therefore, with employee scheduling software, it is possible to foster work-life balance while meeting company goals (Conrad, 2022).
