### ISSUE TITLE
[M1] Appendix A - Use Case Descriptions

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#21]

**Comment by TheRealDexipher** [comment]
![Image](https://user-images.githubusercontent.com/76478315/191668589-57cc243e-cdbf-4384-ba42-36ad808a0fca.png)

**Comment by C0lum** [comment]
[Use Case Descriptions.pdf](https://github.com/SIT-P5-7/ICT2201_P5-7/files/9632356/Use.Case.Descriptions.pdf)
