### ISSUE TITLE
[M1] Appendix B - Data Dictionary

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#22]

**Comment by TheRealDexipher** [comment]
IT
Information Technology means the use of hardware, software, services, and supporting infrastructure to manage and deliver information using voice, data, and video.

UC
A Use Case model is an interaction between the software product itself and the users of that software product(actors). A use case is the specification of a  set of actions performed by a system, which yields an observable result that is typically of value for one or more actors or other stakeholders of the system.

Actors
Actors can be users interacting through Graphical User Interface, users interacting through a command line, components interacting through well-defined API, or components & systems interacting through protocols

PF
A product feature is a specific piece of functionality that has a corresponding benefit or set of benefits for the user. Benefits are the value that users gain from using that functionality.

NFR
Nonfunctional Requirements define system attributes such as security, reliability, performance, maintainability, scalability, and usability. They serve as constraints or restrictions on the design of the system across the different backlogs.

TCF
Technical Complexity Factors are factors that could influence the development of the software. The weight here represents the impact of such a factor. This is given to you. Developers should assess the importance of each factor in their project.

EF
Environmental Factors are several factors in the development environment that could affect the size of a project. 

UCP
Use Case Points is a software estimating approach for forecasting the amount of software for software development activities.

WBS
Work Breakdown Structure is mutually exclusive with planned outcomes, not actions. A task could be broken down into two or more subtasks, but no task should have more than six subtasks.
