### ISSUE TITLE
[M1] References and Acknowledgements

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#3]

**Comment by TheRealDexipher** [comment]
Bhadani, P. (2022) “5 Ways to Improve Business Employee Scheduling”.
https://altametrics.com/en/restaurant-scheduling-software/business-employee-scheduling.html 

11 Best Ways to Use Employee Work Schedule Management. (2016, August 4). Mitrefinch. https://mitrefinch.com/blog/11-best-ways-to-use-employee-work-schedule-management/

Conrad, A. (2022) “Employee Scheduling Software Features and Requirements”.
https://www.selecthub.com/hris/employee-scheduling/employee-scheduling-software-requirements/
