### ISSUE TITLE
[M2] User Interface Requirements

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#37]
Client wants to also see days of the week, no. of hours per day in this table.

It would make more sense if this is based on train schedule?
Manager selects which day -> which trip -> which train -> who to assign

**Comment by SIT-P5-7** [comment]
![Image](https://user-images.githubusercontent.com/112482273/196391726-79d30001-3abe-46ae-b315-5d8ce35a9e30.png)

**Comment by TheRealDexipher** [comment]
Throughout the entire user interface, the design is kept minimalistic and pastel colors were used to create an aesthetically pleasing website as mentioned by the client. Furthermore, we have utilised the Open Sans font as it is often described as neutral and minimalistic, as well as highly readable [4]. All components such as the buttons, navigation bar, dropdown, checkboxes are easy to access and understand as they are uniform and have medium to large dimensions against the user interface screen size. This ensures that the user interface is intuitive and user-friendly.

![Image](https://user-images.githubusercontent.com/76478315/198836637-7edab130-72e7-44fc-81fe-56f00b023e4d.png)

As shown in Figure 2, in the login interface, employees log in using their unique employee ID and password to have authorised access to the system. Employees who forget their login password are able to make a replacement by clicking on the “Forget Password” button.

![Image](https://user-images.githubusercontent.com/76478315/198825749-e202b4f9-000c-4251-900e-f0d0dec238c9.png)

As shown in Figure 3, on the manager landing page, the top 3 lowest workload staff, names, job assigned and working hours for each day of all employees are displayed with the total number of hours indicated at the last column. Staff with over 40 hours of job allocation are highlighted for the manager’s reference to aid in the process of assigning jobs.

**Comment by xinyi-toh** [comment]
![Image](https://user-images.githubusercontent.com/90232197/198826132-ea9b7633-ad03-436e-969c-5cd46f824d9f.png)

As shown in Figure 4, the manager can click on the ‘Job Allocation’ tab and allocate jobs based on factors such as: picking the date of the month in the calendar, selecting the type of trip and type of train. Individual workload hours can be assigned according to the employees and details of their allocated job can be viewed by clicking on the dropdown beside the employee name. 

The workload hours highlighted in red indicates that there is over-assignment. According to Gordon’s job allocation as an Engine Driver, the maximum operating hours of the locomotive is 2 hours at once. Hence, flagging the workload of 3 hours as over-assigned.

**Comment by xinyi-toh** [comment]
![Image](https://user-images.githubusercontent.com/90232197/198826155-13421bba-64e3-40d7-b0ab-3b28d1aaaff5.png)

As shown in Figure 5, under the “Week” tab, the manager is able to view the job allocation table for the week. The system filters all the workload assigned and highlights each cell of the table accordingly, green for assigned and red for over-assigned workload. According to the Employment Act stated under point 3.5, employees are not allowed to work more than 12 hours a day. Thus, the workload of 13 hours for Frank’s schedule on Tuesday is highlighted in red, requiring the manager to make changes to his schedule. Once the schedule is assigned with no highlighted issue, the manager can then click on the ‘Publish’ button to update the new schedule.
