### ISSUE TITLE
[M2] Functional Requirements

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#38]
Most FRs lack details.
Please review.
Refer to lecture slides on 7 traits of requirements as a guide.
"The system shall allow <who> to <do what>..."

**Comment by SIT-P5-7** [comment]
![Image](https://user-images.githubusercontent.com/112482273/196159548-d6eb71de-300d-45c0-bf77-96e88b5b4989.png)

**Comment by TheRealDexipher** [comment]
added requirement 11

![Image](https://user-images.githubusercontent.com/76478315/198282874-a727ef3c-4783-446c-92d9-5cd83ce259d0.png)

**Comment by xinyi-toh** [comment]
edited based on feedback received to provide more details to FR1-10

![Image](https://user-images.githubusercontent.com/90232197/198826047-9f6e1338-58f4-43a5-aeb2-d40441d82aaa.png)
