### ISSUE TITLE
[M1] Client Meeting Minutes

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#4]
Client Meeting Minutes

**Comment by SIT-P5-7** [comment]
Point 2, visualise staff workload on the landing page - create a dashboard? & visualize the staff workload(what is to be shown the workload?) any specifics like hours or days worked during the month
Point 3, manager should be able to allocate jobs to staff for one week at a time - does the staff have a certain amount of working hours per day or can they work like 4 hours one day and 6 hours the next?
Point 4, view staff availability and any other relevant information - what specific information will help with the job assignment process?
Point 5, staff’s location at a particular date - is it where they want to work or where they stay?
Point 6, Sorting system of work by number of hours top down? what does lowest workload represent (no of hours?)
Point 7, display calendar on staff landing page??
Point 8, have a reminder for staff to add and edit their availability?
Point 9, when can staff indicate their job preference for the week? what do you mean by job preference can a cleaner be a train conductor?
Point 10, pop up confirmation to verify if staff has informed management before cancellation?
Point 11, create separate admin access and interface, can the admin make any changes to schedule?
“The route takes approximately 4 hours one way. Engine Driver: at least 1 driver, maximum 2hrs to operate locomotive - require 2 engine drivers in the train for one trip?“
“The manager will make their assignments such that staff should not need to travel between routes” - what routes? 
what is the difference between train conductor and an assistant train conductor? 
what does train conductor and an assistant train conductor do?

**Comment by C0lum** [comment]
[Meeting Minutes.docx](https://github.com/SIT-P5-7/ICT2201_P5-7/files/9556640/Meeting.Minutes.docx)
