### ISSUE TITLE
[M2] Non-Functional Requirements

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#40]
Good effort. Can use MS Quality Attributes as a checklist.

Availability no less than 99.9%
Maintenance can only be done 2am - 4am.

**Comment by xinyi-toh** [comment]
edited NFR2
![Image](https://user-images.githubusercontent.com/90232197/198826240-3882b380-07b8-4f20-a47e-8f468eb539a6.png)
