### ISSUE TITLE
[M2] Performance Requirements

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#41]
Client says 3 seconds response time is ok.

**Comment by SIT-P5-7** [comment]
![Image](https://user-images.githubusercontent.com/112482273/196158587-3d66f52f-e85c-4424-ab57-67d8839477da.png)

**Comment by xinyi-toh** [comment]
edited NFR2 and NFR9

![Image](https://user-images.githubusercontent.com/90232197/198825971-26150a4a-cf60-4c0b-a13c-4f634d5ae44b.png)
