### ISSUE TITLE
[M2] Software Estimation

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#42]
Missing project effort and duration estimation.

**Comment by C0lum** [comment]
1. Project Effort:
The duration estimate refers to the conversion from UCP to FP or Lines of Code (LOC). The range estimation of the hours for each UCP is between 15 to 30 hours. Using this estimate, calculating the estimated effort in developer-hours of a project of size 111 UCP will fall between (15×111) to (30×111) hours. This means the estimated effort will be 1665 to 3330 hours.


2. Duration Estimate:
Using a simple estimation model, the optimistic duration (OD) is the estimation of the minimum amount of time it will take to perform the task, the pessimistic duration (PD) is the estimation of the maximum amount of time it will take to perform the task and the expected duration (ED) is the estimated duration that will be needed to perform the task. In this case, OD will be 4 days, PD will be 13 days and ED will be 6 days. Hence, using the formula D=[(1OD)+(4ED)+(1PD)]/6, D=[(14)+(46)+(113)]/6=6.83.
