### ISSUE TITLE
[M2] Technical Complexity Factors (TCF)

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#44]
Distributed system should be 0 since web app will not be a distributed system.
Easy to install and End user training should be higher since staff are not IT savvy.

**Comment by C0lum** [comment]
![Image](https://user-images.githubusercontent.com/92876235/198824947-37ec0391-10fc-4e51-b07b-13fa63f212fa.jpg)
