### ISSUE TITLE
[M2] Work Breakdown Structure (WBS)

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#45]
No task should have more than 6 subtasks!

**Comment by C0lum** [comment]
![Image](https://user-images.githubusercontent.com/92876235/198824895-903ba158-b861-423f-a58a-f4ef9154f121.jpg)
![Image](https://user-images.githubusercontent.com/92876235/198824896-786250de-6fe7-45b7-a670-9d4d9bfc0af2.jpg)
![Image](https://user-images.githubusercontent.com/92876235/198824897-33be7169-757c-41d9-b87e-5bb01a0d6cbc.jpg)
