### ISSUE TITLE
[M2] Introduction

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#48]
This section will provide a brief description of the product that will be delivered, the product functions, as well as the assumptions and dependencies that the product will have.

**Comment by C0lum** [comment]
In the train operation division, work allocation is assigned weekly every Monday. Therefore, we plan to have an interactive and visualistic workload management web application created for managers to manage employees with ease. This will help ensure employees have an equal amount of workload throughout with their preferred timing indicated for the managers to take into consideration. In this section, you will find the product scope and related background research that was reviewed along with the references, as well as the intended audience and document overview.
