### ISSUE TITLE
[M2] Sequence Diagrams

### ISSUE THREAD

**Issue by TheRealDexipher** [SIT-P5-7/ICT2201_P5-7#58]

**Comment by xinyi-toh** [comment]
create and deactivate account sequence diagram
![Image](https://user-images.githubusercontent.com/90232197/198836885-1b67c286-cebe-4c3e-bec7-94417ea3694f.png)

**Comment by xinyi-toh** [comment]
submit availability sequence diagram
![Image](https://user-images.githubusercontent.com/90232197/198836942-cb5ee3c1-3395-41b1-826d-d7e353a7aa64.png)

**Comment by xinyi-toh** [comment]
edit availability sequence diagram


![Image](https://user-images.githubusercontent.com/90232197/198836976-542df56b-c320-4fd3-b2af-b846ee043ba9.png)

**Comment by xinyi-toh** [comment]
job allocation sequence diagram


![Image](https://user-images.githubusercontent.com/90232197/198837002-85df9ca1-ed7d-4d77-9df7-5557b311b764.png)

**Comment by xinyi-toh** [comment]
view job assignment and reject schedule sequence diagram 



![Image](https://user-images.githubusercontent.com/90232197/198837036-87898a4d-fcc7-4ae0-a6b2-850c440009cc.png)
