### ISSUE TITLE
[M1] Intended Audience and Document Overview

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#6]

**Comment by TheRealDexipher** [comment]
The intended audience will be the client and professors. This document consists of the introduction to the web application that will be created for the staff and managers, a brief description of what the web-based system is supposed to do, product functionality, assumptions that are made, the specific requirements that are for the user, functionality requirements, use case model, non-functional, performance and safety and security requirements. There are also the use case descriptions in Appendix A.

The way this document is supposed to be read is firstly from the Introduction, followed by the description of the product that is going to be created. Next up, will be the requirements that are in the project overview and from the client meeting. The use case model and description (in Appendix A) will be useful to read in this part also. Non-functional requirements and the software estimation will be next to be read. By looking at the Gantt chart, the work breakdown system (WBS) will be easier to understand. For those important keywords in this document, refer to Appendix B.
