### ISSUE TITLE
[M3] Whitebox Testing

### ISSUE THREAD

**Issue by xinyi-toh** [SIT-P5-7/ICT2201_P5-7#61]

**Comment by TheRealDexipher** [comment]
**Pseudo Code for Submit Availability**
![Image](https://user-images.githubusercontent.com/76478315/203992004-99931914-b05d-4d27-b05b-367fc7ac6546.png)

**CFG and Paths**
![Image](https://user-images.githubusercontent.com/76478315/204034724-affdc5a4-f3d5-4ac8-9380-21d4b0d8dbcb.png)

**Test Cases For Different Paths**
![Image](https://user-images.githubusercontent.com/76478315/204034764-90af5233-51a8-4430-a4b9-afef1fec7c1a.png)

**Cyclomatic Complexity Calculation**
M = E - N + 2P
29 - 21 + 2(1) = 10
