### ISSUE TITLE
[M1] Product Overview

### ISSUE THREAD

**Issue by SIT-P5-7** [SIT-P5-7/ICT2201_P5-7#8]

**Comment by TheRealDexipher** [comment]
The product is a new web-based system that is supposed to replace the current job allocating method that is in place right now, providing a simple and convenient system for users to manage their job schedule using an external web server to host the web application which will then save all its data in a separate external cloud database to ensure data will retain in case of data loss.

![Image](https://user-images.githubusercontent.com/76478315/191044266-672d76b2-7a33-4539-9d29-c857638d10a6.png)
